export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINOUTUSER = "LOGINOUTUSERS";
export const SYNCUSERDATA = "SYNCUSERDATA";
export const SETPOSTROOMPROCESS="SETPOSTROOMPROCESS"
export const SETPOSTFLATPROCESS="SETPOSTFLATPROCESS"
export const SETNEEDROOMROCESS="SETNEEDROOMROCESS"
export const SETCOUNTRY="SETCOUNTRY"
